export const ADD_AUCTION = "ADD_AUCTION";
export const READ_AUCTIONS = "READ_AUCTIONS";
export const EDIT_AUCTION = "EDIT_AUCTION";
export const DELETE_AUCTION = "DELETE_AUCTION";
export const AUCTIONS_LOADING = "AUCTIONS_LOADING";